### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Yewx0310** [air158/OfferCat#8]

**Comment by air158** [comment]
请问您在哪个部分遇到了问题，目前我们还在开发，后续会完善readme

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.

**Comment by Yewx0310** [comment]
> 请问您在哪个部分遇到了问题，目前我们还在开发，后续会完善readme

没事了，已经解决

**Comment by air158** [comment]
目前以接入浪潮大模型Yuan2-2B-Mars-hf，生成速度会比星火快，可以尝试一下哦

**Comment by Yewx0310** [comment]
> 目前以接入浪潮大模型Yuan2-2B-Mars-hf，生成速度会比星火快，可以尝试一下哦

后续有计划将这个项目写成一个前后端分离的项目么，对这个项目很感兴趣，可以私信个联系方式么，我的邮箱是wenxue.ye@outlook.com

**Comment by air158** [comment]
有计划的，已私信邮箱
